GET http://localhost:52773/readyai/r4/metadata HTTP/1.1
Content-Type: application/fhir+json
Authorization: Basic U3VwZXJVc2VyOlNZUw==
Accept: application/json

### Create READYAIUser
POST http://localhost:52773/csp/fhirsql/api/ui/v2/credentials
Authorization: Basic U3VwZXJVc2VyOlNZUUw==
Content-Type: application/json

{
  "systemName": "READYAIUser",
  "username": "superuser",
  "password": "SYS",
}

### List all configured credentials
GET http://localhost:52773/csp/fhirsql/api/ui/v2/credentials/
Authorization: Basic U3VwZXJVc2VyOlNZUUw==
Accept: application/json

### Create READYAIRepo in FHIR SQL Builder
POST http://localhost:52773/csp/fhirsql/api/ui/v2/fhirrepository
Authorization: Basic U3VwZXJVc2VyOlNZUUw==
Content-Type: application/json

{
  "name": "READYAIRepo",
  "hostname": "localhost",
  "port": "52773",
  "sslConfig": "",
  "credentialsId": "READYAIUser",
  "repositoryURL": "/readyai/r4"
}

### List all FHIR repositories
GET http://localhost:8080/csp/fhirsql/api/ui/v2/fhirrepository/
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Accept: application/json

### Create Analysis in FHIR SQL Builder
POST http://localhost:8080/csp/fhirsql/api/ui/v2/analysis
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

{
  "fhirRepositoryId": 4
}

###
GET http://localhost:8080/csp/fhirsql/api/ui/v2/analysis/
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

###
GET http://localhost:8080/csp/fhirsql/api/ui/v2/analysis?ID=1
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

### Create Transformation

POST http://localhost:8080/csp/fhirsql/api/ui/v2/transformspec
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

{
  "name": "Transform",
  "scanId": 4,
  "description": "",
  "resources": [
    {
      "resourceType": "Patient",
      "columns": [
        {
          "name": "GivenName",
          "type": "String",
          "path": "Patient.name.given",
          "index": false,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "PatientNameGiven"
        },
        {
          "name": "FamilyName",
          "type": "String",
          "path": "Patient.name.family",
          "index": false,
          "dataIndex": false,
          "length": 50,
          "RENAMED": "PatientNameFamily"
        },
        {
          "name": "PatientIdentifierValue",
          "type": "String",
          "path": "Patient.identifier.where(type.coding.system = 'http://terminology.hl7.org/CodeSystem/v2-0203').value",
          "index": true,
          "dataIndex": false,
          "length": 50
        },
        {
          "name": "Gender",
          "type": "String",
          "path": "Patient.gender",
          "index": true,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "PatientGender"
        },
        {
          "name": "BirthPlaceCity",
          "type": "String",
          "path": "Patient.extension.where(url = 'http://hl7.org/fhir/StructureDefinition/patient-birthPlace').valueAddress.city",
          "index": false,
          "dataIndex": false,
          "length": 50,
          "RENAMED": "PatientPatientBirthPlaceValueAddressCity"
        },
        {
          "name": "BirthPlaceCountry",
          "type": "String",
          "path": "Patient.extension.where(url = 'http://hl7.org/fhir/StructureDefinition/patient-birthPlace').valueAddress.country",
          "index": false,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "PatientPatientBirthPlaceValueAddressCountry"
        },
        {
          "name": "City",
          "type": "String",
          "path": "Patient.address.city",
          "index": false,
          "dataIndex": false,
          "length": 50,
          "RENAMED": "PatientAddressCity"
        },
        {
          "name": "PostalCode",
          "type": "String",
          "path": "Patient.address.postalCode",
          "index": false,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "PatientAddressPostalCode"
        },
        {
          "name": "Country",
          "type": "String",
          "path": "Patient.address.country",
          "index": false,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "PatientAddressCountry"
        }
      ]
    },
    {
      "resourceType": "Condition",
      "columns": [
        {
          "name": "Patient",
          "type": "String",
          "path": "Condition.subject.reference",
          "index": true,
          "dataIndex": false,
          "length": 50,
          "RENAMED": "ConditionSubjectReference"
        },
        {
          "name": "Status",
          "type": "String",
          "path": "Condition.clinicalStatus.coding.code",
          "index": false,
          "dataIndex": false,
          "length": 10,
          "RENAMED": "ConditionClinicalStatusCodingCode"
        },
        {
          "name": "Description",
          "type": "String",
          "path": "Condition.code.text",
          "index": false,
          "dataIndex": false,
          "length": 100,
          "RENAMED": "ConditionCodeText"
        },
        {
          "name": "SnomedCode",
          "type": "String",
          "path": "Condition.code.coding.code",
          "index": true,
          "dataIndex": false,
          "length": 50
        }
      ]
    }
  ],
  "version": 1,
  "scanStartDateTime": "2025-10-09T09:54:09Z",
  "scanFHIRRepositoryName": "READYAIRepo",
  "id": 4,
  "lastModified": "2025-10-09T12:57:10.263Z"
}

### Get All Transformations
GET http://localhost:8080/csp/fhirsql/api/ui/v2/transformspec/
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

### Create Projection

POST http://localhost:8080/csp/fhirsql/api/ui/v2/projection
Authorization: Basic U3VwZXJVc2VyOlNZUzEyMw==
Content-Type: application/json

{
    "fhirRepositoryId": 4,
    "specificationId": 4,
    "packageName": "READYAI"
}