services:
  iris:
    build:
      context: ./iris
    env_file:
      - .env
    ports:
    - 1973:1972
    - 8888:8888
    volumes:
    - ./iris/projects:/home/irisowner/dev
    restart: unless-stopped

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2025.3
    hostname: localhost
    container_name: iris-wg-2
    ports:
    - "32783:80"
    - "32784:443"
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./iris/resources/webgateway:/webgateway-shared

  langchain:
    build:
      context: ./langchain_external
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./langchain_external:/app
    restart: unless-stopped