services:
  iris:
    build:
      context: ./iris
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
    - 1973:1972
    - 8888:8888
    # - 32783:52773
    volumes:
    - ./iris/projects:/home/irisowner/dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "iris", "session", "IRIS", "-U", "READYAI", "halt"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2025.3
    hostname: localhost
    ports:
    - "32783:80"
    - "32784:443"
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared

  langchain:
    build:
      context: ./langchain_external
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - ./langchain_external:/app
    restart: unless-stopped
